### ISSUE TITLE
Stable tag

### ISSUE THREAD

**Issue by pdoreau** [FBerthelot/angular-images-resizer#10]
Hello. Thanks for this great module !
Is the master branch stable ? I can see an out of date dependency status : [![devDependency Status](https://david-dm.org/FBerthelot/angular-images-resizer/dev-status.svg)](https://david-dm.org/FBerthelot/angular-images-resizer#info=devDependencies)
Also I'd like to use the png output format.
Can you publish a stable tag ?
Thanks,

**Comment by FBerthelot** [comment]
Hello,
You're welcome :)
The master branch is stable (The codeship status shows that the branch is stable, all tests are passing).
The devDependencies status is only for dependencies needed for the development of this module.
If I update my devDependencies, my tests won't pass anymore due to a problem of loading image in phantomJS...
But there is no problem with my module, just with the tools I've use to develop it.

You can use the png output format by the way (i've recently released this functionality ;) ). You can use outputFormat option in resizeImage function.

ps: I love your nickname :)

**Comment by pdoreau** [comment]
I see and I noticed the availability of outputFormat param.
However, installed version by bower install is 1.0.0. Creating a new tag could make usable the features currently in master.

**Comment by FBerthelot** [comment]
Oh ok, my bad... I though my last tag was up to date with the master branch.
I've release the 1.0.1 version which is up to date :)
